[phases.setup]
nixPkgs = ["python312", "python312Packages.pip", "gobject-introspection", "cairo", "pango", "gdk-pixbuf", "libffi", "fontconfig", "freetype", "harfbuzz"]

[phases.install]
cmds = ["python3.12 -m pip install -r requirements.txt"]

[start]
cmd = "python3.12 -m uvicorn app:app --host 0.0.0.0 --port $PORT"
